rootProject.name = "shade"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("auth")
include("button")
include("cli")
include("core")
include("devices")
include("discover")
include("entertainment")
include("events")
include("grouped-lights")
include("homekit")
include("internals")
include("lightlevel")
include("lights")
include("resources")
include("rooms")
include("scenes")
include("serialization")
include("structures")
include("zones")
