[versions]
kimchi = "1.1.0"

[libraries.publishing]
version = "1.0.0"
module = "com.inkapplications.publishing:ink-publishing"

[libraries.spondee]
version = "0.6.0"
module = "com.inkapplications.spondee:measures"

[libraries.subatomic]
version = "1.1.0"
module = "com.inkapplications.subatomic:core"

[libraries.kimchi-logger]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:logger"

[libraries.kimchi-core]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:core"
