[versions]
kimchi = "2.0.0"

[libraries.publishing]
version = "1.0.0"
module = "com.inkapplications.publishing:ink-publishing"

[libraries.spondee]
version = "0.8.1"
module = "com.inkapplications.spondee:units"

[libraries.kimchi-logger]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:logger"

[libraries.kimchi-core]
version.ref = "kimchi"
module = "com.inkapplications.kimchi:core"
