[versions]
kotlin = "1.7.20"
coroutines = "1.6.4"

[libraries.gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.coroutines-test]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"

[libraries.serialization-plugin]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-serialization"

[libraries.serialization-json]
version = "1.3.3"
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"

[libraries.datetime]
version = "0.4.0"
module = "org.jetbrains.kotlinx:kotlinx-datetime"

[libraries.test-junit]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-junit"

[libraries.test-core]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test"

[libraries.test-annotations]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-test-annotations-common"

[libraries.dokka]
version.ref = "kotlin"
module = "org.jetbrains.dokka:dokka-gradle-plugin"

[libraries.kotlinx-binary-compatibility]
version = "0.13.1"
module = "org.jetbrains.kotlinx:binary-compatibility-validator"
