[versions]
ktor = "2.0.3"

[libraries.client-core]
version.ref = "ktor"
module = "io.ktor:ktor-client-core"

[libraries.serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.client-contentnegotiation]
version.ref = "ktor"
module = "io.ktor:ktor-client-content-negotiation"

[libraries.client-okhttp]
version.ref = "ktor"
module = "io.ktor:ktor-client-okhttp"

[libraries.okhttp-tls]
version = "4.9.3"
module = "com.squareup.okhttp3:okhttp-tls"

[libraries.client-js]
version.ref = "ktor"
module = "io.ktor:ktor-client-js"
