[versions]
ktor = "2.2.1"
okhttp = "4.9.3"

[libraries.client-core]
version.ref = "ktor"
module = "io.ktor:ktor-client-core"

[libraries.serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.client-contentnegotiation]
version.ref = "ktor"
module = "io.ktor:ktor-client-content-negotiation"

[libraries.client-okhttp]
version.ref = "ktor"
module = "io.ktor:ktor-client-okhttp"

[libraries.okhttp-tls]
version.ref = "okhttp"
module = "com.squareup.okhttp3:okhttp-tls"

[libraries.okhttp-sse]
version.ref = "okhttp"
module = "com.squareup.okhttp3:okhttp-sse"

[libraries.client-js]
version.ref = "ktor"
module = "io.ktor:ktor-client-js"

[libraries.client-curl]
version.ref = "ktor"
module = "io.ktor:ktor-client-curl"

[libraries.client-darwin]
version.ref = "ktor"
module = "io.ktor:ktor-client-darwin"

[libraries.client-cio]
version.ref = "ktor"
module = "io.ktor:ktor-client-cio"

[libraries.client-winhttp]
version.ref = "ktor"
module = "io.ktor:ktor-client-winhttp"
