name: Latest Build
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v1
            -
                name: Build
                run: ./gradlew build
            -
                name: Prepare Archives
                run: cp cli/build/distributions/shade-*.zip cli/build/distributions/shade.zip && cp cli/build/distributions/shade-*.tar cli/build/distributions/shade.tar
            -
                name: Archive CLI Tar
                uses: actions/upload-artifact@v1.0.0
                with:
                    name: shade.tar
                    path: cli/build/distributions/shade.tar
            -
                name: Archive CLI Zip
                uses: actions/upload-artifact@v1.0.0
                with:
                    name: shade.zip
                    path: cli/build/distributions/shade.zip
